# Generated by Django 2.1.4 on 2018-12-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpmapper',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cpmapper',
            name='vicinities',
        ),
        migrations.RemoveField(
            model_name='vpmapper',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vpmapper',
            name='vicinities',
        ),
        migrations.AddField(
            model_name='cpmapper',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpmapper',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AddField(
            model_name='vpmapper',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AddField(
            model_name='vpmapper',
            name='vicinity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Vicinity', unique=True),
            preserve_default=False,
        ),
    ]
