# Generated by Django 2.1.4 on 2018-12-21 14:51

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20181221_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
