# Generated by Django 2.1.4 on 2018-12-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_attribute_type_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(to='product.Category')),
                ('cities', models.ManyToManyField(to='product.City')),
            ],
        ),
    ]
