# Generated by Django 2.1.4 on 2018-12-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20181221_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appmanager',
            old_name='categories',
            new_name='_categories',
        ),
        migrations.RenameField(
            model_name='appmanager',
            old_name='cities',
            new_name='_cities',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='_parent',
        ),
        migrations.RenameField(
            model_name='cpmapper',
            old_name='products',
            new_name='_products',
        ),
        migrations.RenameField(
            model_name='cvmapper',
            old_name='vicinities',
            new_name='_vicinities',
        ),
        migrations.RenameField(
            model_name='vicinity',
            old_name='city',
            new_name='_city',
        ),
        migrations.RenameField(
            model_name='vpmapper',
            old_name='products',
            new_name='_products',
        ),
    ]
