# Generated by Django 2.1.4 on 2018-12-24 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20181223_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmanager',
            name='_categories',
        ),
        migrations.RemoveField(
            model_name='appmanager',
            name='_cities',
        ),
        migrations.RemoveField(
            model_name='category',
            name='_parent',
        ),
        migrations.RemoveField(
            model_name='cpmapper',
            name='_products',
        ),
        migrations.RemoveField(
            model_name='cvmapper',
            name='_vicinities',
        ),
        migrations.RemoveField(
            model_name='vicinity',
            name='_city',
        ),
        migrations.RemoveField(
            model_name='vpmapper',
            name='_products',
        ),
        migrations.AddField(
            model_name='appmanager',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.Category'),
        ),
        migrations.AddField(
            model_name='appmanager',
            name='cities',
            field=models.ManyToManyField(blank=True, to='product.City'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='product.Category'),
        ),
        migrations.AddField(
            model_name='cpmapper',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AddField(
            model_name='cvmapper',
            name='vicinities',
            field=models.ManyToManyField(blank=True, to='product.Vicinity'),
        ),
        migrations.AddField(
            model_name='vicinity',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vpmapper',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
